# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9ba2ea64b3e78caf2055271d9fb97e026c66815d247a25e348f9be997d9f56a781d9aee67aa4c9628f93ed5bdbfc9a7915c5f08afc000adf3a7c999362c5f2

test:
  secret_key_base: caa144d0951170355b61986c58683718bd8fbb7251c0bc732f162529f6c8eee11af4e26cebe3e6f548cd3518b59d8edfc2d420c2baf7b1564a53e4d90fa9249f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
